{
  imports = [
    ./alpha.nix
    ./bufferline.nix
    ./barbecue.nix
    ./chadtree.nix
    ./colorscheme.nix
    #./floaterm.nix
    ./indent-blankline.nix
    ./illuminate.nix
    ./lualine.nix
    ./neo-tree.nix
    ./notify.nix
    ./noice.nix
    ./nui.nix
    ./toggleterm.nix
    ./todo-comments.nix
    ./wrapping.nix
    ./which-key.nix
  ];
}
